[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes', 'vim-fugitive']
hook_add = '''
    execute 'source' . g:dein_config_dir . 'vim-airline.vim'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

