[[plugins]]
repo = 'tyru/caw.vim'
on_event = ['VimEnter']
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'caw.vim'
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim") || has("python3")'
on_event = ['InsertEnter']
build = '''
    if has("python3")
        echo 'install neovim python3'
        sudo pip install neovim
    endif
'''
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'deoplete.vim'
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'neosnippet.vim'
'''

[[plugins]]
repo = 'lervag/vimtex'
on_event = ['VimEnter']
on_ft = 'tex'
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'vimtex.vim'
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'
hook_add = '''
    let g:previm_open_cmd = 'firefox --new-window'
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

# [[plugins]]
# repo = 'zchee/deoplete-jedi'
# on_ft = ['python']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
