[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'deoplete.vim'
'''

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['tpope/vim-fguitive']
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'lightline.vim'
'''

[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'vim-quickhl.vim'
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'nerdtree.vim'
'''

# [[plugins]]
# repo = 'Shougo/denite.nvim'
# hook_add = '''
#     execute 'source ' . g:dein_config_dir . 'denite.vim'
# '''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'vim-indent-guides.vim'
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'gitgutter.vim'
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    colorscheme molokai
'''

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# [[plugins]]
# repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'deoplete-plugins/deoplete-dictionary'
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'deoplete-dictionary.vim'
'''

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
    execute 'source ' . g:dein_config_dir . 'vim-lsp-settings.vim'
'''
